version: '3.7'

volumes:
  eu-revendedor__vm__node-modules:
    driver: local
  eu-revendedor__vm__mongo:
    driver: local

services:
  api:
    build:
      context: ./api
      target: development
    restart: always
    container_name: eu-revendedor__server
    working_dir: /usr/src/app
    command: npm run start:dev
    env_file:
      - .env
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PASS: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DATABASE}
    depends_on:
      - mongo
    volumes:
      - ./api:/usr/src/app
      - eu-revendedor__vm__node-modules:/usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_PORT_DEBUG}:${SERVER_PORT_DEBUG}
  
  mongo:
    image: mongo
    container_name: eu-revendedor__mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - eu-revendedor__vm__mongo:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  
  mongo-express:
    image: mongo-express
    container_name: eu-revendedor__mongo-express
    restart: always
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
